---
title: "Himalayan Tahrs"
author: "Dionée du Toit"
date: "2025-02-27"
output: html_document
---
In this project I am plotting Himalayan Tahr sightings on Table Mountain. This could aid in assessing the effects that the invasive Himalayan Tahrs have on native ecosystems. The data is from iNaturalist. 
```{r}
## load all the packages
options(repos = c(CRAN = "https://cloud.r-project.org/"))
install.packages("rinat")
install.packages("sf")
install.packages("prettymapr")
install.packages("htmltools")
install.packages("leaflet", type = "binary")
install.packages("mapview")
install.packages("leafpop")

library(rinat)
library(tidyverse)
library(sf)
library(rosm)
library(ggspatial)
library(prettymapr)
library(leaflet)
library(htmltools)
library(mapview)
library(leafpop)

```

```{r}
##Load data from iNaturalist into R
ht <- get_inat_obs(taxon_name = "Hemitragus jemlahicus",
                   bounds = c(-34, 18.34, -33.94, 18.46),
                   maxresults = 1000)
```

```{r}
##Filter data
ht <- ht %>% filter(positional_accuracy<46 & 
                      latitude<0 &
                      !is.na(latitude) &
                      captive_cultivated == "false" &
                      quality_grade == "research")
```

```{r}
##convert to spatial data frame
ht <- st_as_sf(ht, coords = c("longitude", "latitude"), crs = 4326)
```

```{r}
##Creating basic map with ggplot2
ggplot() + geom_sf(data=ht)
```
```{r}
## Overlay the Data on an OpenStreetMap Base Layer
ggplot() + 
  annotation_map_tile(type = "osm", progress = "none") + 
  geom_sf(data=ht)
```
```{r}
##Create an interactive map with leaflet
leaflet() %>%
  # Add default OpenStreetMap map tiles
  addTiles(group = "Default") %>%  
  # Add our points
  addCircleMarkers(data = ht,
                   group = "Hemitragus jemlahicus",
                   radius = 2, 
                   color = "purple") 

```
```{r}
##Create an interactive map with mapview
mapview(ht, 
        col.regions = "darkgreen",  # Change color
        popup = popupTable(ht, zcol = c("user_login", "captive_cultivated", "url")))
```
```{r}
##Add clickable links to observations
Hemitragus_jemlahicus <- ht %>%
  mutate(click_url = paste("<b><a href='", url, "'>Link to iNat observation</a></b>"))
mapview(Hemitragus_jemlahicus,
        col.regions = "darkgreen",  
        popup = 
          popupTable(Hemitragus_jemlahicus,
                     zcol = c("user_login", "captive_cultivated", "click_url")))
```

